######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 25 18:27:12 2009
######################################################################

TEMPLATE = app
CONFIG -= app_bundle
QT += network gui 
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += LineEdit.h PlayBus.h
SOURCES += main.cpp
